UKHomeOffice/ima

- apps/ima/behaviours/save-image.js
-'Why are you submitting this form late?' textarea input is removed if upload button is clicked before continue/save and exit button [IMB-97](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-97)
- Textarea input is removed if upload button is clicked before continue/save and exit button and even with text it shows error message
- New constant latesubmissiondetails is declared in save-image.js. If it exist then set in the session model in setValues method.
- In ValidationField method ValidationError is modified with image instead of key.
> IMB-97 textarea input removed bug fix

- test/_unit/server.spec.js
Stub the 'Cases' method import in server.js test file.
Importing this file and using its class appears to be trying to connect the test environment to AWS by updating the configuration and creating an S3 object.
There is no variables available in test to do this so it throws and error. Confusingly the AWS function seems to run async so its error is thrown into other tests in the runner. Hopefully this stubbing will stop the attempted connection and allow all tests to run without errors being thrown as a side-effect.
Stubs fine locally when AWS values are removed from code.
> Fix: Stub Cases method in server spec

- apps/ima/fields/index.js
- apps/ima/translations/src/en/validation.json
- Validation on Full Name [IMB-92](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-92)
- Validation on fullname Enter Full Name as URL or email format still accepted, and no error is shown  in you-location  flow
- NoURL is added as validation in fields / index.js
- In validation.json file error messages were added to name 
> IMB-92 Validation on fullname

- apps/ima/index.js
- apps/ima/views/evidence-upload.html
- apps/ima/views/partials/form.html
- assets/scss/app.scss
-Save and Exit button missing from the page as per FIGMA  [IMB-73](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-73)
- Save and Exit button missing in the summary page, in-line with Sigma
- Save and Exit button already exist in master but the spacing between Continue and Save and Exit button is not the same as in GDS. So changed the space with save-and exit-button  SCSS in form.html (partials) and using margin-left with 15 px. It is global change and it will be reflected in all the pages.
- In evidence upload page Save and Exit button spacing is changed in line with other pages with div removed and in index.js showSaveAndExit: true is added in evidence-upload
> IMB-73 Save and exit button bug fix

- apps/verify/index.js
-Back button missing from the page as per FIGMA  [IMB-76](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-76)
- Back button missing in the details not found page, in-line with Figma
- Backlink: 'your-details' added in details not found  in index.js
> IMB-76-back-button-missing-bug-fix

- apps/ima/index.js
- Page not found bug fix [IMB-116](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-116)
- When we press back button in removal-condition it goes to page not found instead of exception page
-  Removed / in backlink and use exception  instead of /exception in removal-condition in index.js
> IMB-116-page-does-not-exist-bug-fix

- .drone.yml
- Dockerfile
What?
 I've added Trivy Scanner to Pipeline and removed deprecated Anchore Scanner for the IMA  service, see ticket
[https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-437](url)
Why?
Trivy will let you scan images, file systems and repositories for any vulnerabilities and issues. It will detect CVEs of OS packages, applications susceptibilities, and exposures of IaC in Terraform files, Kubernetes and Docker. Drawback of Anchore Scanner is it’s significantly slower, the process of using it is more cumbersome, the output is less friendly and most importantly, it scans fewer CVEs. 
How?
 Removed Anchore cve exception file and added trivy cve exception file in hof-services-config repo from IMA configs. Removed Anchore Scanner steps from pipeline and added trivy scanner steps with cron …
> WIP -DO NOT MERGE - HOFF-437: Replace Anchore with Trivy

- apps/ima/behaviours/check-email-token.js
- apps/ima/behaviours/continue-report.js
- apps/ima/behaviours/resume-form-session.js
- apps/ima/behaviours/save-form-session.js
- apps/ima/index.js
- apps/ima/models/cases.js
- apps/ima/sections/summary-data-sections.js
- apps/ima/translations/src/en/fields.json
- apps/ima/translations/src/en/pages.json
- apps/ima/views/cases.html
- apps/ima/views/content/form-submitted.md
- apps/verify/behaviours/send-verification-email.js
- apps/verify/behaviours/validate-case-details.js
- apps/verify/fields/index.js
- apps/verify/index.js
- apps/verify/translations/src/en/fields.json
- apps/verify/translations/src/en/validation.json
- apps/verify/views/content/not-found.md
- apps/verify/views/your-details.html
- bin/upload_cases_sheet.sh
- config.js
- db/get-token.js
- db/save-token.js
- lib/xlsx-processor.js
- test/_unit/db/get-token.spec.js
- test/_unit/ima/behaviours/check-email-token.spec.js
- test/_unit/verify/behaviours/send-verification-email.spec.js
- Add CEPR/DOB verification to the beginning of the IMA form [IMB-87](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-87)
- Change configuration of the database, replacing 'uan' with 'cepr', and adding the new column 'duty-to-remove-alert' [IMB-88](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-88)
- Set the 'Duty to Remove alert' value in the session [IMB-89](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-89)
- To verify that the combination of CEPR and DOB exists
- To use the CEPR now instead of UAN (as part of the wider database changes to replace UAN with CEPR)
- To allow the ban-only/DTR forking in the form [IMB-85](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-85), as designed in Figma
- Modify validation to cater for CEPR (6-10 digits) in …
> IMB-87-89: Add CEPR/DOB verification and set 'duty to remove alert' value in session

- Dockerfile
- apps/ima/behaviours/check-email-token.js
- apps/ima/behaviours/resume-form-session.js
- apps/ima/behaviours/save-form-session.js
- apps/ima/translations/src/en/pages.json
- apps/verify/behaviours/validate-case-details.js
- config.js
- kube/hof-rds-api/deployment.yml
- Add ban-only / Duty to Remove branch to the IMA form flow [IMB-85](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-85)
- To allow the ban-only/DTR forking in the form
- To match the flow designed on Figma
- Get the 'duty to remove alert' value from the session in /db/get-token.js
- Add conditional logic to index.js, using the session's 'duty to remove alert' value, to determine the flow
- Update /kube/hof-rds-api/deployment.yml with the latest Quay image ID that contains the new database column change
> IMB-85: Add ban-only / DtR branch

- apps/ima/fields/index.js
- apps/ima/index.js
- apps/ima/sections/summary-data-sections.js
- apps/ima/views/temporary-permission.html
- Amend the 'Information you have given us' (`final-summary`) page to include the `temporary-permission` screen section, as part of the DTR/ban-only flow [IMB-45](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-45)
- For the user to be able to view information they have provided for the DTR/ban-only flow
- For the content to match the Figma designs
- Add new section to /sections/summary-data-sections.js for the `temporary-permission` screen
- Add conditional logic to summary-data-sections.js to determine the value to be displayed in the temporary permission section
- Add the DTR/ban-only temporary permission page's field into pages.json
- Add conditional logic to the `immigration-detention` and `medical-records` pages in index.js, to enable the flow to fork based on the duty to …
> IMB-45: Amend the 'Information you have given us' page for the ban-only flow

- bin/deploy.sh
- kube/hof-rds-api/deployment.yml
- Update image used for hof-rds-api deployment.
- Remove the ability for branch environment to deploy cronjobs from `/kube/cron` folder
- Relates [IMB-144](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-144)
- The new image for hof-rds-api will allow the latest knex migration to run and add the new `cepr_lookup` table to the database. This new table is required for the hof-db-table-replacer to run.
- Cron jobs were enabled temporarily in branch env to test a new job and can now be removed to avoid spawning many identical jobs. 
Updated kubernetes deployment file for hof-rds-api and the generic `deploy.sh` script.
> IMB-144: Update hof-rds-api image and remove branch deployment of cronjobs

- kube/cron/hof_db_table_replacer.yaml
Update the image used for hof-db-table-replacer cron jobs to the latest created.
This image is the master branch with all MVP supporting tickets merged into it.
> IMB-144 Update hof-db-table-replacer to latest image

- Dockerfile
Remove PSQL from the Dockerfile in IMA - [IMB-125](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-125)
To remove PSQL from the IMA UAT environment
Remove the '`apk add postgresql`' command from the Dockerfile
Tested for removal of PSQL in branch
> IMB-125: Remove PSQL from the Dockerfile

- apps/ima/behaviours/create-and-send-pdf.js
- apps/ima/behaviours/submit.js
- apps/ima/translations/src/en/pages.json
- apps/ima/views/content/form-submitted.md
- apps/ima/views/form-submitted.html
- apps/ima/views/pdf.html
- assets/scss/app.scss
- config.js
Add functionality to send an email with a PDF on submission of the IMA form - [IMB-29](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-29)
For the IMA users to receive a confirmation email of the form submission including a PDF of their answers, with the email being sent to the immigration adviser too if they are specified on the form
- amend GovNotify submission email template to match the latest designs
- change `/behaviours/create-and-send-pdf.js` to use the updated GovNotify template and to pass it the correct parameters from the form, and to remove redundant logic
- amend `/behaviours/submit.js` to retrieve all the unique emails that are relevant for the email-sending functionality
- amend confirmation page's wording in `pages.json` and `form-submitted.md` to match the latest …
> IMB-29: Add PDF confirmation email to IMA

- .drone.yml
- bin/deploy.sh
- bin/image_check.sh
- kube/app/deployment.yml
- kube/cron/hof_db_table_replacer.yaml
- kube/file-vault/file-vault-deployment.yml
- kube/hof-rds-api/deployment.yml
- kube/hof-rds-api/ingress.yml
Deployments in Stage env are using Production secrets for rds and s3. Now We have added a condition for deployments in stage to use the secrets(s3 bucket, rds secret) of Branch/UAT env. Updated Secret name from ima-prod to ima-rds-prod to give a meaningful context.
Cron jobs enabled in Stage env.
Production url has been added  
Removed Anchore-inline scanner which has reached End Of Life ( as mentioned in anchore website). We have also removed it from all the services.
We are setting up Stage and Production environment.  Deployments in stage and prod requires secrets of s3 bucket and rds instances.
dataservice ingress url in production depends on the production url. 
Added conditions wherever necessary in the deployment files to refer the secrets which are supposed to be used. …
> IMB-111: Update repo for using Stage env

- .snyk
- apps/ima/index.js
IMA report - Declaration data not tracked - [IMB-172](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-172)
- The csv file did not show all the saved values of declaration data
- So that the user can view the saved session values of declaration data correctly in the csv file in reports
- add SaveFormSession behaviour to '/declaration',  '/immigration-adviser-declaration' and '/helper-declaration' in index.js
- SNYK file changes for vulnerability SNYK-JS-BRACES-6838727
Tested locally
> IMB-172 csv file bug fix

- .snyk
- bin/deploy.sh
- kube/hof-rds-api/ingress.yml
We are replacing External Ingress with Internal Ingress for data service. data service is backend service and cannot be externally accessed with external ingress. 
Team have decided to use internal ingress. All the Policy admissions added to the namespaces to allow internal ingress which is now pointing to the internal ingress of ACP.  Route53 is configured for the internal ingress
Added Internal Ingress Annotations to the Internal Ingress used by Data Service 
This file is added in Hof-service-config git repo
IMA (with Data service as internal ingress) is Tested in Branch Env by QAT team. They have approved us to progress to UAT. After tested Okay without issues we promote these changes to Stage and then to Prod (Progressive Approach)
We have updated in deploy.sh to use Internal Ingress …
> IMB-111: Update Ingress for data-service

- apps/ima/views/temporary-permission.html
Update wording on the temporary-permission screen - [IMB-159](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-159)
To match the latest Figma designs
- remove first paragraph in `temporary-permission.html`
Tested locally and in branch
> IMB-159: Temporary permission screen wording change

- kube/app/deployment.yml
- kube/cron/hof_db_table_replacer.yaml
- kube/file-vault/file-vault-deployment.yml
- kube/hof-rds-api/deployment.yml
ACP team have created S3 buckets and RDS instance for Stage. Secrets have been added to the namespaces. We need our code to reference the secrets added in namespace. I have added the conditions for stage to use the secrets of S3 and RDS instances
Stage deployments are unable to connect the RDS instances and s3 buckets used for branch and UAT env. ACP team have suggested us to create one for Staging. These Stage S3 buckets and RDS instance in stage are identical to prod. Performance testing will be done on staging so should be identical (AWS resources. pods etc) to prod. Using lower environment AWS resources is ruled out
deployment.yaml for all the deployments have references to these secrets. They have been updated including the cron jobs. 
The only way to test these is by deploying into …
> IMB-111: Add Secret ref for Stage Environment

- apps/ima/behaviours/aggregator-save-update.js
- apps/ima/behaviours/harm-claim-summary.js
- apps/ima/behaviours/limit-countries.js
- apps/ima/behaviours/modify-change-link.js
- apps/ima/behaviours/reset-harm-claim-summary.js
- apps/ima/behaviours/save-form-session.js
- apps/ima/index.js
- apps/ima/sections/summary-data-sections.js
- apps/ima/views/confirm.html
- apps/ima/views/harm-claim-countries.html
- apps/ima/views/harm-claim-details.html
- apps/ima/views/risk-of-harm.html
**Fix issues caused by pressing the browser back button on the IMA SIH section:**
- Fix bug where user is able to add more than five countries  - [IMB-156](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-156)
- Fix bug where user is able to add an SIH country with a blank title after deleting an SIH country (observed while testing the fix for IMB-156)
**Fix routing logic on the SIH section**
- To prevent the ability to add more than five countries to the SIH section
- To prevent the adding of a record in the SIH section without a title
- To correct the routing issues on the SIH section
- add logic in `/behaviours/aggregator-save-update.js` to prevent the adding of a country if there are already five in the list, or if the country being added has a blank title
- add an 'undefined' …
> IMB-156: Fix bug of exceeding SIH country limit

- apps/ima/behaviours/set-static-emails.js
- apps/ima/views/content/form-submitted.md
- config.js
- hof.settings.json
- test/_unit/server.spec.js
Add the queries email to the IMA form-submitted page - [IMB-161](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-161)
So the user is provided information on the email address to send further evidence to
- add 'queriesEmail' property to `config.js` to pull the email address value from the secrets file
- add `/behaviours/enquiries-email-local.js` to pull the email address from `config.js`
- include the enquiries-email-local.js behaviour in `hof.settings.json`
- add the 'queriesEmail' variable into `/views/content/form-submitted.md` to populate the email address on the form-submitted page
- add the new enquiries-email-local.js behaviour to `/test/_unit/server.spec.js` as part of the 'Setup HOF Configuration' test case
Tested locally and in branch
> IMB-161: Add email to the form submitted page

- apps/ima/translations/src/en/pages.json
Add email address to Medical Records content - [IMB-191](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-191)
Email address is not showing under the Medical Records content
Email address {{queriesEmail}} has been added to the medical-records in pages.json so that queriesEmail will be populated dynamically from env variables
Testing done locally
> IMB-191 Add email address to Medical Records content

- apps/ima/views/partials/head.html
- apps/verify/views/partials/head.html
Add robots meta tag to de-index the entire IMA form - [IMB-189](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-189). Similarly done for ETA ([ETA-123](https://collaboration.homeoffice.gov.uk/jira/browse/ETA-123))
So that the form is not returned in browser searches
- add the `/ima/views/partials/head.html` file with the 'robots noindex' meta tag to ensure it is added to the head section of all the form's pages
- add the '/verify/views/partials/head.html' file the same as the one above
Tested locally and in branch
**Verify flow:**
**Main flow:**
> IMB-189: De-index IMA webform

- apps/ima/sections/summary-data-sections.js
500 Internal server error [IMB-204](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-204)
-  When the user is on the 'Are there any other reasons you should be granted temporary permission to stay in the UK?' page and they click on 'Yes', then click on 'Human Rights' and type something in the text box, click continue and then click continue on the upload evidence page without uploading any documents they receive a 500 internal server error.
- In summary-data-section.js in  temporary-permission-to-stay section typeof(req.sessionModel.get('temporary-permission-reasons')) === 'object' was checked for join and if it is string join was not used
> IMB-204 Internal server error

- apps/common/views/content/accessibility.md
[IMB-208-accessibility-statement-fix ](https://collaboration.homeoffice.gov.uk/jira/browse/IMB-208)
 
Accessibility statement needs addition line spaces
 
- \ was added between the sentence; 'listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)' & 'We have also made the website text as simple as possible to understand.'. 
- In the Enforcement Procedure section, <p> was added  in between  'contact the Equality Advisory and Support Service (EASS). ' and the following sentence
- In the Non-compliance with the accessibility regulations section <br> was added between the heading on the section and the start on the first paragraph
-  in the Non-compliance with the accessibility regulations section the WCAG standards and timelines …
> IMB-208 Accessibility statement fix
